import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

export const boxApi = createApi({
  reducerPath: "boxApi",
  baseQuery: fetchBaseQuery({
    baseUrl: "http://10.0.60.55:5003/v1",
    prepareHeaders: (headers) => {
      const token = localStorage.getItem("token");
      if (token) {
        headers.set("Authorization", `Bearer ${token}`);
      }
      return headers;
    },
  }),
  endpoints: (builder) => ({
    getAllBox: builder.query({
      query: () => "/box/retrieve",
    }),
    updateBox: builder.mutation({
      query: ({ _id, data }) => ({
        url: `/box/customize/${_id}`,
        method: "PATCH",
        body: data,
      }),
    }),
  }),
});

// Export the hook generated by RTK Query
export const { useGetAllBoxQuery,useUpdateBoxMutation} = boxApi;

export default boxApi